# Generated by Django 5.2.6 on 2025-10-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_created_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='def.jpg', null=True, upload_to='product_photo'),
        ),
    ]
