# Generated by Django 5.2.6 on 2025-10-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='def.jpg', null=True, upload_to='category_photo'),
        ),
    ]
